name: "datanorma_dbt"
version: "1.0.0"
config-version: 2

profile: "datanorma"

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  datanorma_dbt:
    marts:
      +materialized: table
