apiVersion: v1
kind: Service
metadata:
  name: datanorma
spec:
  selector:
    app: datanorma
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
